# release workflow
name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up golang
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
          check-latest: true
          cache: true
      - name: build-linux
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release -f .goreleaser-linux.yml --rm-dist
      - name: build-darwin
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release -f .goreleaser-darwin.yml --rm-dist
      - name: build-win
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release -f .goreleaser-win.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}